### PR TITLE
Deprecate scala.util.parsing.json

### PR DESCRIPTION
**Pull request by janekdb**
https://github.com/scala/scala-parser-combinators/issues/99

 - [x] Add json package with deprecation comments and link to The Scala Library Index
 - [x] Add deprecation to every top-level class/object in the package

### CODE REVIEW

**Comment by janekdb** [comment]
@gourlaysama - This is WIP. Please comment on the approach,

 * Add json package with deprecation comments and link to _The Scala Library Index_
 * Add `@deprecation` to every member

For now just one member has a deprecation annotation to get early feedback.

Along the way I came across https://issues.scala-lang.org/browse/SI-3115 when I tried to deprecate the package object instead of deprecating every member.

**Comment by sjrd** [comment]
IMO every top-level class/object in the package should be deprecated.

**Comment by janekdb** [comment]
@sjrd - Yes, this looks like the very least that should be done.

**Comment by gourlaysama** [comment]
Yes, please deprecate everything in `json/{Lexer,Parser}.scala` too.

👍 for the package-level doc that explains things :)

**Comment by janekdb** [comment]
All top level entities deprecated.

parsing-json-deprecated

**Comment by SethTisue** [comment]
PR'ed to scala/scala for 2.12.3: https://github.com/scala/scala/pull/5880

**Pull request merged**
