### PR TITLE
Update scala 2.12.8 to 2.12.9

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by SethTisue** [comment]
not sure what to make of the Travis-CI error

**Comment by SethTisue** [comment]
Travis-CI has been very flaky lately over in the ScalaCheck repo, presumably it's the same here and this will be okay to merge after we hit "restart" enough times on the failing job(s). I just hit "restart" on the one red job.

**Comment by Philippus** [comment]
I cleared the repository cache in Travis CI and it got farther than before, still not green though.

**Comment by Philippus** [comment]
And now it's green.

**Pull request merged**
