### PR TITLE
[wip] version bump for sbt-scala-module (for Java 9)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
my immediate motivation is that I'm working on getting the Scala 2.12 community build running on Java 9, and the sbt-scala-module bump is needed for that.

the Scala.js version bump is just for good measure.

**Comment by SethTisue** [comment]
yuck — the Travis failure looks to be the result of the Scala.js bump. I'll downgrade.

**Comment by SethTisue** [comment]
sigh. we can hold off on merging this, since it doesn't get us all the way to a working Java 9 build — we're blocked by https://github.com/scala/sbt-scala-module/issues/35

**Comment by gourlaysama** [comment]
The module version was bumped in #135, and java 9 now works out of the box: #142! 🎉

**Comment by SethTisue** [comment]
nice.

**Pull request closed without merging**
