### PR TITLE
remove long-deprecated scala.util.parsing.json

### LINKED ISSUE #221: drop util.parsing.json
it would remain on 1.1.x, we'd drop it for 1.2.x

it's been deprecated for quite a while now

@Philippus wdyt?

part of the reason I'm interested is that it would make it easier to add a Dotty cross-build

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #221

### CODE REVIEW

**Comment by SethTisue** [comment]
@Philippus the only hesitation I have here is that some of the removed tests might not actually about JSON support, they might just be using the JSON support as a convenient way to test something else. wdyt?

**Comment by Philippus** [comment]
related:

https://github.com/scala/scala/pull/124

https://github.com/scala/scala/commit/302612f3341f66fa0f9b458b4496ff9b69906a5b

**Comment by SethTisue** [comment]
@Philippus thanks. I don't see a need to dig further

**Comment by SethTisue** [comment]
we'll see what NAUGHTY, BAD projects in the Scala community build were still using this somewhere (hopefully none)

**Pull request merged**
