### PR TITLE
Scala 2.13.0-M4 -> M5 (and publish)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
this is blocked, and publishing is blocked, until Scala.js is published for 2.13.0-M5

**Comment by xuwei-k** [comment]
I think there is an another problem. We can't use jdk6 for dependency resolution 😕 
- https://github.com/scala/scala-collection-compat/issues/77
- https://blog.sonatype.com/enhancing-ssl-security-and-http/2-support-for-central
- https://jfrog.com/knowledge-base/why-am-i-failing-to-work-with-jfrog-saas-service-with-tls-1-0-1-1/
- https://travis-ci.org/scala/scala-parser-combinators/jobs/422673037#L623

```
	Server access Error: Received fatal alert: protocol_version url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.17/sbt-0.13.17.pom
	Server access Error: Received fatal alert: protocol_version url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.17/sbt-0.13.17.jar
	Server access Error: Connection reset url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.17/ivys/ivy.xml
	Server access Error: Connection reset url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.17/ivys/ivy.xml
```

**Comment by xuwei-k** [comment]
> We can't use jdk6

https://github.com/scala/scala-parser-combinators/issues/169

**Comment by milessabin** [comment]
Is there anything I can help to move this along? It's blocking the shapeless release for 2.13.0-M5 ...

**Comment by SethTisue** [comment]
I will try to get this done today/tomorrow. (Unless I end up having to report for jury duty tomorrow, in which case I'll try to find someone else on the Scala team to do it.)

**Comment by SethTisue** [comment]
CI is green except for JDK 6 (#169). so, merging.

**Comment by SethTisue** [comment]
new ticket on just the publishing part, now: https://github.com/scala/scala-parser-combinators/issues/170

**Pull request merged**
