### PR TITLE
Add an irrefutable version of the NoSuccess extractor

### PR DESCRIPTION
**Pull request by lrytz**
NoSuccess.unapply cannot be changed due to binary compatibility.

### CODE REVIEW

**Comment by lrytz** [comment]
Binary compatibility checks fail because of the new definition, I assume if this goes to a version 2.2.x it should be fine?

**Comment by SethTisue** [comment]
> I assume if this goes to a version 2.2.x it should be fine

We currently have `versionPolicyIntention` set to backwards-compat-only `BinaryCompatible` (rather than to the stricter `BinaryAndSourceCompatible` for bidirectional compat), so I think we need to take seriously the possibility that MiMa is right to reject the change.

The failure looks like:

```
[error]  * abstract method NoSuccessE()scala.util.parsing.combinator.Parsers#NoSuccessE# in interface scala.util.parsing.combinator.Parsers is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("scala.util.parsing.combinator.Parsers.NoSuccessE")
```

If I understand `ReversedMissingMethodProblem` correctly, it's complaining because a method was added to an interface. Doing so isn't backwards binary compatible because existing classes that implement that interface will lack an implementation for the new method.

Must the new extractor be nested inside `Parsers`?

**Comment by lrytz** [comment]
Thanks Seth, I failed to challenge my assumptions...

Added a nested extractor `case NoSuccess.I(msg, next)`, that has better ergonomics as well. Should `NoSuccess.unapply` be deprecated to help people find the new one?

**Comment by SethTisue** [comment]
Um, hmm, judgment call... I'm a bit tempted to say just Scaladoc it rather than deprecate, but really, I'm on the fence. @Philippus opinion?

**Comment by dwijnand** [comment]
The exhaustivity already functions as a heads up.  So doc it, I agree.

**Comment by SethTisue** [comment]
@lrytz shall I roll a release?

**Comment by lrytz** [comment]
Yes thanks!

**Pull request merged**
