### PR TITLE
Allow building an existing tag against a new Scala version

### PR DESCRIPTION
**Pull request by lrytz**
For tags of the form `v1.2.3-suffix#2.13.0-M1`, the build script
releases version `1.2.3-suffix` using Scala version `2.13.0-M1`.

This allows building an existing tag against a new Scala version.

### CODE REVIEW

**Comment by lrytz** [comment]
Same patch as in scala/scala-swing#59, already used successfully.

We should then merge 1.0.x into master to get this in the other branch.

**Comment by lrytz** [comment]
I realize I need to do something about `crossScalaVersions` and the fact that travis triggers builds on multiple java versions, will come back to it.

**Comment by gourlaysama** [comment]
> I realize I need to do something about `crossScalaVersions` and the fact that travis triggers builds on multiple java versions

Yeah, that complicates everything, see #86.

**Comment by lrytz** [comment]
@gourlaysama I included your changes from https://github.com/scala/scala-parser-combinators/pull/111, this should be good to go now.

**Comment by gourlaysama** [comment]
@lrytz that last commit won't work until scala-js for 2.13.0-M1 is released, but the rest LGTM.

**Comment by lrytz** [comment]
Thanks! I heard scala-js should happen soon, so we can wait if that's fine for you.

**Comment by gourlaysama** [comment]
🎉!

**Comment by lrytz** [comment]
Nice! We'll have to get this into the `master` branch. I quickly checked, there's quite a number of commits that went into 1.0.x that aren't in master yet:

```
> export mb=$(git merge-base 1.0.x master)
> git log --graph --oneline --decorate $mb..1.0.x | cat
*   0da708b (upstream/1.0.x, 1.0.x) Merge pull request #109 from lrytz/tag-with-scala-version
|\
| * 26d971a (origin/tag-with-scala-version, tag-with-scala-version) Also cross-build against 2.13.0-M1
| * 6cac8c3 Allow building an existing tag against a new Scala version
|/
*   eb5bc9a Merge pull request #106 from gourlaysama/improve-scaladoc-output
|\
| * 6ca3c3d Improve parser combinator documentation
* |   f09b0ec Merge pull request #102 from Zandbee/patch-1
|\ \
| |/
|/|
| * 399bbb8 Update Getting_Started.md
* |   d118db9 Merge pull request #103 from janekdb/issue/github/99/deprecate-scala.util.parsing.json
|\ \
| |/
|/|
| * 7815fd9 Deprecate scala.util.parsing.json
|/
*   5ec6af9 Merge pull request #100 from gourlaysama/travis-caching
|\
| * d901210 speed up Travis builds using caching feature
|/
*   cf326ad Merge pull request #98 from ladinu/patch-1
|\
| * f1a47ee Syntax highlight
|/
*   d0d847d Merge pull request #96 from raboof/getting_started
|\
| * f536e54 Add Getting Started example to the README
| * 48dc032 Move 'Getting Started' guide to separate file
| * 7df76d7 Add "Getting Started" section to README
|/
*   04a2f50 Merge pull request #95 from SethTisue/odersky-venners-spoon
|\
| * 0e3326f link to Programming in Scala from README.md
* |   5d733ef Merge pull request #94 from gourlaysama/update-post-1.0.5
|\ \
| |/
|/|
| * c0dabd9 Update version and README for v1.0.5
* |   94e25a3 Merge pull request #93 from raboof/patch-1
|\ \
| |/
|/|
| * 33792d3 Add link to 'Building a lexer and parser with Scala's Parser Combinators'
| * fbf3d08 Update latest API link, add getting started link
|/
* acddd21 (tag: v1.0.5) Merge pull request #92 from gourlaysama/bump4
* 6c52b6a bump scala, sbt & scala-js dependency versions
```

Should all of these be merged forward?

Also, to be more in line with scala/scala and other module repos, should we rename `master` to `1.1.x`?

**Comment by lrytz** [comment]
ping @gourlaysama - no rush, just to know if you saw comment above?

**Comment by gourlaysama** [comment]
I just pushed v1.0.6, but publishing partially failed (2.11 and 2.12 were published, but not 2.13.0-M1), see https://travis-ci.org/scala/scala-parser-combinators/builds/227935497

**Comment by gourlaysama** [comment]
Ah, it tried to publish the root project...

**Comment by gourlaysama** [comment]
And [everything is green][1].

The staging repositories are:
 - 2.12 and 2.13.0-M1: https://oss.sonatype.org/service/local/repositories/orgscala-lang-1420/content/
 - 2.11: https://oss.sonatype.org/service/local/repositories/orgscala-lang-1419/content/

Could you also close the two older staging repos (from the first try): orgscala-lang-1417 and orgscala-lang 1418?

[1]: https://travis-ci.org/scala/scala-parser-combinators/builds/227952683

**Comment by gourlaysama** [comment]
@lrytz I have just tested those jars and everything seems ok. All that's left is promoting the two repos and waiting for them to get to maven central :)

**Comment by lrytz** [comment]
@gourlaysama promoted. Thanks a lot!

**Pull request merged**
