### PR TITLE
Speed up line/column in OffsetPosition

### PR DESCRIPTION
**Pull request by liskin**
Building the index again and again for every OffsetPosition instance makes
very little sense.  So this makes it build it only once for a given source.

I'm not sure if this is the best way to implement it and I'm afraid that a
global synchronized map may be a performance bottleneck once the number of
processors goes into the hundreds, but I know very little Scala/Java to do
this properly. :-(

Fixes
http://stackoverflow.com/questions/14707127/accessing-position-information-in-a-scala-combinatorparser-kills-performance

### CODE REVIEW

**Comment by liskin** [comment]
Any idea what to do with the mima errors? Shall I use a differently named object with package-private members or are those warnings false?

**Comment by gourlaysama** [comment]
That's why I was more into the re-submission of the PR, cherry-picking into 1.0.x seemed too good to be true...

Hmm, this is one of those annoying things with the companion object of a case class. I think that adding `extends scala.runtime.AbstractFunction2[CharSequence,Int,OffsetPosition]` to the object should be enough (untested; running `sbt test` will invoke mima). Sorry about the added process, I guess I could I done that myself...

**Comment by liskin** [comment]
Oh, that indeed fixes it! I would never have figured that out myself. :-)

**Comment by gourlaysama** [comment]
Yay! That's one of those things that one only remembers because of the pain it caused in the past (for reference, [SI-4808][1] and [SI-3664][2]).

LGTM

[1]: https://issues.scala-lang.org/browse/SI-4808
[2]: https://issues.scala-lang.org/browse/SI-3664

**Pull request merged**
