### PR TITLE
adapt to scala/scala#9292

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
first commit was my first naive stab, second commit was after I looked at it a bit closer

**Comment by som-snytt** [comment]
🩸 🔪 🙈

**Comment by som-snytt** [comment]
I would like to make the same offer as posco on twitter ("if you would like me to leave suggestions and comments"), except with puns and emoji.

**Comment by SethTisue** [comment]
two puns please, and a side order of emoji, hold the pickle

**Comment by SethTisue** [comment]
squashed. regardless of what happens to scala/scala#9292, I think this is code improvement and we should just merge it.

**Review by Philippus — APPROVED** [review]

**Pull request merged**
