### PR TITLE
Favour `p` to `q` in `|||` parser if consuming same #chars

### LINKED ISSUE #72: `|||` should resolve a tie by choosing `this` parser rather than `q`
`if (next2.pos < next1.pos)` should be `if (next2.pos <= next1.pos)` (or equivalently `if (next1.pos >= next2.pos)`, which I feel is more readable and consistent with the specification that the ''longest'' is chosen.)

### PR DESCRIPTION
**Pull request by Philippus**
fixes #72

### CODE REVIEW

**Comment by SethTisue** [comment]
@Philippus can you rebase and see if that makes CI green?

**Comment by Philippus** [comment]
there's one job in the matrix failing

**Comment by SethTisue** [comment]
I hit "restart" and it was green on the next try. 🤷

**Comment by SethTisue** [comment]
@Philippus https://contributors.scala-lang.org/t/reviewers-wanted-for-scala-parser-combinators-prs/2041 didn't produce any reviewers. shall we just merge this, do you think?

**Comment by Philippus** [comment]
The behaviour of the `|||`-parser changes so maybe this should also target a 1.2.x branch?

**Comment by SethTisue** [comment]
> maybe this should also target a 1.2.x branch?

one could argue it either way, I think, but targeting a 1.2.x branch does seem like the safe/conservative choice

I've opened https://github.com/scala/scala-parser-combinators/issues/188 to have a broader discussion about maybe branching

**Comment by Philippus** [comment]
rebased onto the `1.2.x` branch

**Pull request merged**
