### PR TITLE
bump scala, sbt & scala-js dependency versions

### PR DESCRIPTION
**Pull request by gourlaysama**
A bit late, after this PR I'll be able to tag and release v1.0.5.

### CODE REVIEW

**Comment by gourlaysama** [comment]
@SethTisue I pushed the `v1.0.5` tag, and Travis has pushed the 4 jars to Sonatype 🎉 
```
resolvers += "Sonatype1381" at
"https://oss.sonatype.org/service/local/repositories/orgscala-lang-1381/content/"

resolvers += "Sonatype1382" at
"https://oss.sonatype.org/service/local/repositories/orgscala-lang-1382/content/"
```

The build is marked failed in Travis because it also tried to publish the root project of the multi-project build, which it shouldn't.

**Comment by SethTisue** [comment]
cool, so you want me to go ahead and close and publish those staging repos?

**Comment by gourlaysama** [comment]
Yes please :)
I did a quick test of both JVM and JS artifacts and everything seems to work.

**Comment by SethTisue** [comment]
I did "Close" and "Release" on both repos in the Sonatype web UI, so the artifacts should be on their way to Maven Central now.

**Comment by SethTisue** [comment]
troubles in Sonatype land, seems to have affected this as well https://issues.sonatype.org/browse/MVNCENTRAL-1423 https://twitter.com/alexelcu/status/810844155454877697

**Comment by SethTisue** [comment]
hmm though, the artifacts are there at e.g. http://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/ , they just haven't been indexed by search.maven.org yet...

**Comment by SethTisue** [comment]
search.maven.org finally picked this up

**Pull request merged**
