### PR TITLE
Fix StackOverflowError in PagedSeq.fromString

### LINKED ISSUE #178: Passing large input to PagedSeq.fromString causes StackOverflowError
test case:
```
        val len = 10000
        val i = Iterator.fill(len)("A")
        val pagedSeq = PagedSeq.fromStrings(i)
        pagedSeq.slice(1)
```

error:
```
[error] Test scala.util.parsing.input.gh64.test failed: java.lang.StackOverflowError: null, took 0.006 sec
[error]     at scala.util.parsing.input.PagedSeq$.more$1(PagedSeq.scala:51)
[error]     at scala.util.parsing.input.PagedSeq$.more$1(PagedSeq.scala:50)
[error]     at scala.util.parsing.input.PagedSeq$.more$1(PagedSeq.scala:50)
[error]     at scala.util.parsing.input.PagedSeq$.more$1(PagedSeq.scala:50)
[error]     at scala.util.parsing.input.PagedSeq$.more$1(PagedSeq.scala:50)
[error]     at scala.util.parsing.input.PagedSeq$.more$1(PagedSeq.scala:50)
[error]     at scala.util.parsing.input.PagedSeq$.more$1(PagedSeq.scala:50)
[error]     at scala.util.parsing.input.PagedSeq$.more$1(PagedSeq.scala:50)
...
```

### PR DESCRIPTION
**Pull request by filipochnik**
Fixes #178

### CODE REVIEW

**Comment by filipochnik** [comment]
What do these test failures mean?

**Comment by Philippus** [comment]
Seems not related to this PR, looks like something's changed with TravisCI related to installing JDK's.

**Comment by SethTisue** [comment]
I opened https://github.com/scala/scala-parser-combinators/issues/181 on the JDK 6 thing

**Comment by SethTisue** [comment]
@filipochnik can you rebase and see if that makes CI green?

**Comment by SethTisue** [comment]
review by @Philippus and/or @gourlaysama?

**Pull request merged**
