### PR TITLE
backport new publishing scripts based on sbt-ci-release

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by SethTisue** [comment]
I assume your "help me backport module publishing to an earlier branch" offer at the Scala Spree didn't get any takers :-)

**Comment by lrytz** [comment]
The updated MiMa seems to find some binary incompatibilities
```
[info] Compiling 22 Scala sources to /home/travis/build/scala/scala-parser-combinators/jvm/target/scala-2.12/test-classes ...

[error]  * static method numberParser()java.lang.ThreadLocal in class scala.util.parsing.json.JSON does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.util.parsing.json.JSON.numberParser")

[error]  * static method defaultNumberParser()scala.Function1 in class scala.util.parsing.json.JSON does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.util.parsing.json.JSON.defaultNumberParser")

[error]  * static method keywordCache()scala.collection.mutable.HashMap in class scala.util.parsing.json.JSON does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.util.parsing.json.JSON.keywordCache")
```

@Philippus does that look legitimate?

**Comment by Philippus** [comment]
I think it could be an example of https://github.com/lightbend/mima/issues/388?

**Comment by SethTisue** [comment]
Agree. Those sources didn't change, and 1.1.0 was built with 2.12.4. It's fine to exclude the failures.

**Comment by lrytz** [comment]
Created a test tag (https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.3-test-1%23prefix-dotty-js), travis builds (https://travis-ci.org/scala/scala-parser-combinators/builds/655834831) and staging repos looked good.

**Pull request merged**
