### PR TITLE
for 1.2.x, drop Scala 2.11 support (including Scala Native)

### PR DESCRIPTION
**Pull request by SethTisue**
Scala Native support could be re-added once SN supports Scala 2.12 and/or 2.13

### CODE REVIEW

**Comment by SethTisue** [comment]
@Philippus It just seems like a maintenance burden to me. I don't have my heart set on merging this, though. wdyt?

2.11 support would remain in place on the 1.1.x branch

**Comment by Philippus** [comment]
I'm okay with it, but this will not cause problems for https://github.com/lightbend/ssl-config for example?
If there is an important bugfix we could always backport it to the 1.1.x branch.

**Comment by SethTisue** [comment]
I think ssl-config could themselves be dropping 2.11 support at this point. But anyway yeah exactly, the 1.1.x branch still exists, in the unlikely event we need it.

**Review by Philippus — APPROVED** [review]

**Comment by SethTisue** [comment]
Hmm.... 2.13 support for Scala Native support was just merged. I hadn't anticipated that happening so quickly after 2.12 support landed.

So perhaps it would be better to wait a little while longer for a Scala Native release, then redo this PR to drop 2.11 but without dropping Scala Native.

**Comment by Philippus** [comment]
Awesome! Good that I stalled on reviewing. ;)

**Comment by SethTisue** [comment]
okay, closing for now, we can always reopen later

**Pull request closed without merging**
