### PR TITLE
Revert scala native support

### PR DESCRIPTION
**Pull request by gourlaysama**
- Reverts scala-native support (#118)
 - updates scala & plugin dependencies

Then we can release 1.0.7.

### CODE REVIEW

**Comment by gourlaysama** [comment]
See https://github.com/scala/scala-parser-combinators/issues/130#issuecomment-361931300.

**Comment by gourlaysama** [comment]
@SethTisue  [the build][1] succeeded, and the two staging repos on sonatype are `orgscala-lang-1464` and `orgscala-lang-1465`.

[1]: https://travis-ci.org/scala/scala-parser-combinators/builds/335714576

**Comment by gourlaysama** [comment]
@SethTisue can you Close and Release the two staging repos in sonatype?

**Comment by gourlaysama** [comment]
I'll push the tag to publish for 2.13.0-M3 in a few hours, not all maven central mirrors have picked up scala-js-0.6.22_2.13.0-M3 yet...

**Comment by SethTisue** [comment]
yup, hopefully today, else tomorrow

**Comment by SethTisue** [comment]
let's continue on #130

**Pull request merged**
