### PR TITLE
Add support for Scala.js, with cross-compilation.

### PR DESCRIPTION
**Pull request by sjrd**
Scala versions were upgraded to 2.11.7 and 2.12.0-M3. 2.12 is only used when running the build on JDK8 or later.

`JavaTokenParsers.identifier` was rewritten not to use a regexp, but rather primitive parsers and `Character.isJavaIdentifier{Start,Part}`. The regexp-based implementation relies on Java-specific character ranges.

`JavaTokenParsers.stringLiteral` was slightly adapted with an expansion of `\p{Cntrl}` into `[\x00-\x1F\x7F]`. The former character range is Java-specific. We also removed an invalid (and useless) `+` at the end of the regexp.

The test `t4929.scala` is JVM-only.

### CODE REVIEW

**Comment by sjrd** [comment]
Ping @gourlaysama

**Comment by gourlaysama** [comment]
Thanks for the ping, I'll have a look tomorrow.

Oh, this might need some things to change in the /admin stuff used for publishing.

**Comment by sjrd** [comment]
Unless I overlooked something, /admin is fine. I made sure that the root project aggregates the JS and JVM versions, so that `+test` tests both, for example, and `+publishSigned` publishes both.

**Comment by gourlaysama** [comment]
LGTM

**Comment by sjrd** [comment]
Thanks!

**Pull request merged**
